import html2canvas from "html2canvas-pro";
import { jsPDF } from "jspdf";

const REPORT_PAGE_COUNT = 11;
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const PAGE_MARGIN = 18;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;

const formatDate = (date = new Date()) => {
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}-${month}-${year}`;
};

const formatDateTime = (date = new Date()) =>
  date.toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

const sanitizeFileName = (name = "") =>
  String(name)
    .trim()
    .replace(/[^a-zA-Z0-9]/g, "");

const captureElement = async (element) => {
  if (!element) return null;

  const canvas = await html2canvas(element, {
    scale: 3,
    useCORS: true,
    allowTaint: true,
    backgroundColor: "#ffffff",
    logging: false,
  });

  return canvas.toDataURL("image/png");
};

const chartSections = [
  {
    key: "performanceTrend",
    title: "Performance Trend",
    subtitle: "Attempt-by-attempt percentage",
    notes: [
      "This line shows how your percentage changes from one attempt to the next.",
      "An upward pattern suggests improving performance; repeated dips identify attempts worth reviewing.",
    ],
  },
  {
    key: "examAttempts",
    title: "Exam Attempts",
    subtitle: "Practice volume by exam",
    notes: [
      "This chart compares how often you have practised each exam category.",
      "Use it to spot categories that need a more regular practice schedule.",
    ],
  },
  {
    key: "bestVsAverage",
    title: "Best vs Average Performance",
    subtitle: "Peak and typical percentage by exam",
    notes: [
      "The gap between best and average performance indicates how consistently you perform.",
      "A smaller gap means your usual result is closer to your strongest attempt.",
    ],
  },
  {
    key: "practiceDistribution",
    title: "Practice Time Distribution",
    subtitle: "Exam-wise learning time",
    notes: [
      "Each segment represents the share of total practice time spent on an exam.",
      "Compare the time invested with outcomes to decide where to rebalance effort.",
    ],
  },
  {
    key: "timeEfficiency",
    title: "Time Efficiency",
    subtitle: "Time spent compared with percentage",
    notes: [
      "This visual helps relate the time used in an attempt to the score achieved.",
      "Look for efficient attempts that deliver strong percentages without excessive time.",
    ],
  },
  {
    key: "scoreDistribution",
    title: "Score Distribution",
    subtitle: "Attempts grouped by percentage range",
    notes: [
      "This chart shows the percentage bands in which most of your attempts fall.",
      "A shift toward higher bands over time is a clear indicator of progress.",
    ],
  },
  {
    key: "examRadar",
    title: "Exam-wise Performance Radar",
    subtitle: "Average and best performance across exams",
    notes: [
      "The radar compares average and best percentages across every exam category.",
      "It makes relative strengths and areas needing attention easy to identify at a glance.",
    ],
  },
  {
    key: "cumulativeTrend",
    title: "Cumulative Average Trend",
    subtitle: "Running average across attempts",
    notes: [
      "The running average smooths individual results to show your longer-term direction.",
      "A rising line points to sustained improvement rather than a one-off high score.",
    ],
  },
  {
    key: "weekdayActivity",
    title: "Practice Activity by Day",
    subtitle: "Attempts completed on each weekday",
    notes: [
      "This chart highlights the days on which you tend to practise most often.",
      "Use it to build a steadier routine and protect lower-activity study days.",
    ],
  },
  {
    key: "consistency",
    title: "Consistency Score",
    subtitle: "Score stability across attempts",
    notes: [
      "The consistency score estimates how stable your performance is across attempts.",
      "Improving consistency helps make results more reliable under exam conditions.",
    ],
  },
];

const addHeader = (doc, sectionLabel) => {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, PAGE_WIDTH, 24, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text("EXAMPLAT", PAGE_MARGIN, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.text(sectionLabel, PAGE_WIDTH - PAGE_MARGIN, 15, { align: "right" });
};

const addFooter = (doc, pageNumber) => {
  doc.setDrawColor(226, 232, 240);
  doc.line(PAGE_MARGIN, 282, PAGE_WIDTH - PAGE_MARGIN, 282);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by ExamPlat e-Examination Platform", PAGE_MARGIN, 288);
  doc.text(`Page ${pageNumber} of ${REPORT_PAGE_COUNT}`, PAGE_WIDTH - PAGE_MARGIN, 288, {
    align: "right",
  });
};

const addSummaryPage = (doc, { studentName, summary }) => {
  addHeader(doc, "ANALYTICS REPORT");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(15, 23, 42);
  doc.text("Performance Overview", PAGE_MARGIN, 46);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Prepared for ${studentName || "Student"}`, PAGE_MARGIN, 54);
  doc.text(`Generated ${formatDateTime()}`, PAGE_MARGIN, 60);

  const metrics = [
    ["Total Mock Tests", summary.totalAttempts ?? 0],
    ["Average Percentage", `${summary.averagePercentage ?? 0}%`],
    ["Highest Percentage", `${summary.bestPercentage ?? 0}%`],
    ["Lowest Percentage", `${summary.lowestPercentage ?? 0}%`],
    ["Questions Attempted", summary.totalQuestionsAttempted ?? 0],
    ["Practice Time", summary.practiceTimeFormatted || "0 min"],
  ];

  metrics.forEach(([label, value], index) => {
    const column = index % 2;
    const row = Math.floor(index / 2);
    const x = PAGE_MARGIN + column * 87;
    const y = 75 + row * 38;

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, y, 79, 29, 3, 3, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(label, x + 6, y + 10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(String(value), x + 6, y + 21);
  });

  doc.setDrawColor(226, 232, 240);
  doc.line(PAGE_MARGIN, 202, PAGE_WIDTH - PAGE_MARGIN, 202);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("How to read this report", PAGE_MARGIN, 216);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const overview = doc.splitTextToSize(
    "The following ten pages each focus on one visual from your analytics dashboard. Review the pattern, then use the brief interpretation to decide what to sustain, improve, or practise next.",
    CONTENT_WIDTH
  );
  doc.text(overview, PAGE_MARGIN, 225, { lineHeightFactor: 1.5 });
  addFooter(doc, 1);
};

const addChartPage = (doc, chart, pageNumber) => {
  addHeader(doc, "ANALYTICS VISUAL");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.setTextColor(15, 23, 42);
  doc.text(chart.title, PAGE_MARGIN, 43);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(chart.subtitle, PAGE_MARGIN, 50);

  const chartTop = 62;
  const chartWidth = CONTENT_WIDTH;
  const chartHeight = 130;
  if (chart.image) {
    const image = doc.getImageProperties(chart.image);
    const ratio = image.width / image.height;
    let width = chartWidth;
    let height = width / ratio;
    if (height > chartHeight) {
      height = chartHeight;
      width = height * ratio;
    }
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(PAGE_MARGIN, chartTop, chartWidth, chartHeight, 3, 3, "S");
    doc.addImage(chart.image, "PNG", PAGE_MARGIN + (chartWidth - width) / 2, chartTop + (chartHeight - height) / 2, width, height);
  } else {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(PAGE_MARGIN, chartTop, chartWidth, chartHeight, 3, 3, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("Visual data is not available for this report.", PAGE_WIDTH / 2, chartTop + chartHeight / 2, { align: "center" });
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("What this visual shows", PAGE_MARGIN, 211);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const explanation = doc.splitTextToSize(chart.notes.join(" "), CONTENT_WIDTH);
  doc.text(explanation, PAGE_MARGIN, 221, { lineHeightFactor: 1.55 });
  addFooter(doc, pageNumber);
};

/**
 * Generates an 11-page analytics report: one overview page and one page per visual.
 */
export const downloadAnalyticsReport = async ({
  studentName = "",
  summary = {},
  chartRefs = {},
}) => {
  try {
    const chartImages = await Promise.all(
      chartSections.map((chart) => captureElement(chartRefs[chart.key]))
    );

    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    addSummaryPage(doc, { studentName, summary });
    chartSections.forEach((chart, index) => {
      doc.addPage();
      addChartPage(doc, { ...chart, image: chartImages[index] }, index + 2);
    });

    const safeName = sanitizeFileName(studentName) || "Student";
    const fileName = `Analytics_Report_${safeName}_${formatDate()}.pdf`;
    doc.save(fileName);

    return { success: true, fileName };
  } catch (error) {
    console.error("Analytics Report Generation Error:", error);
    throw error;
  }
};
